### ISSUE TITLE
[1.0.5] Crashes if Baubles not present

### ISSUE THREAD

**Issue by asiekierka** [BenjaminSutter/genera#17]
The dependency should be explicitly listed if intended.

[17:07:08] [main/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.2-1.12.2-anarchy.jar)
  MageCoremod (MAGE-0.1.1.jar)
  CharsetPatchCore (CharsetPatches-0.1.4.jar)
  FMLPlugin (Mirage-2.0.3-rc3.jar)
  BedPatch (bedpatch-2.1-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 2/19/18 5:07 PM
Description: Initializing game

java.lang.NoClassDefFoundError: net/bms/genera/items/ItemConnlaRing
	at net.bms.genera.event.EventHandler.registerItems(EventHandler.java:72)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_198_EventHandler_registerItems_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:739)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:604)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassNotFoundException: net.bms.genera.items.ItemConnlaRing
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 25 more
Caused by: java.lang.NoClassDefFoundError: baubles/api/IBauble
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 27 more
Caused by: java.lang.ClassNotFoundException: baubles.api.IBauble
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 31 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 33 more

**Comment by BenjaminSutter** [comment]
Interesting. I really thought I worked around that. Thanks for the report Asie. I'll get right to it. I hope you like the mod when I do. Happy to see someone using it!

**Comment by BenjaminSutter** [comment]
Fixed in the latest commit. Release is processing on Curse.

**Comment by asiekierka** [comment]
>Happy to see someone using it!

I didn't get to use it yet. I just wanted to test it out.

**Comment by BenjaminSutter** [comment]
Still, thanks for the report. 1.0.6 is still under review on CurseForge.
